README.md
Please also fix it in repository description.
=> Fix typo in domain name

LICENSE, package.json
=> #13 Using by-nc-nd license over MIT license

package.json, src/assets/css/main.scss, src/assets/css/shared.scss, src/assets/js/main.ts, src/views/index.ejs, src/views/layout/footer.ejs, src/views/layout/header.ejs, tailwind-config.js, tsconfig.json, webpack.config.js
=> Frontpage Port

package-lock.json, package.json, src/assets/css/_mep.scss, src/assets/css/main.scss, src/assets/js/main.ts, src/assets/js/mep.ts, src/views/contact-your-mep.ejs, src/views/index.ejs, src/views/layout/footer.ejs, src/views/layout/header.ejs
=> Contact your MEP page

src/app.ts, src/config.ts, src/views/index.ejs
- Fix for tweets
- Listen on localhost only
=> Ejs & express fix

package-lock.json, src/assets/css/shared/_global-components.scss, src/views/layout/header.ejs, tailwind-config.js
=> Fix header overflow issue

src/assets/css/_mep.scss, src/assets/js/mep.ts, src/views/contact-your-mep.ejs
Remaining MEPs slide into position after changing the filter.
I think this looks much nicer overall and less clunky
=> Nicer MEP List

README.md, package-lock.json, package.json, src/app.ts, src/config.ts, src/controllers/gallery.ts, src/controllers/router.ts, src/views/layout/header.ejs
Added and fixed a lot of stuff:
- Added github webhook 
- Added command execution for webhook
- Fixed Gallery error: "Can't set headers after they are sent."
- Generally refactored gallery controller
- Moved routes from app.ts to /controller/router.ts
- Strip language query string from URL 
- Added Webhook things to config 
- Added a title to the header
- Added auto-generated titles for subsites / subroutes 
- Fixed language handler (read cookie data)
=> Webhook route & a lot of changes 

package-lock.json, package.json, src/assets/css/main.scss, src/views/layout/header.ejs, webpack.mix.js
=> Transform Lang Picker String to Image

README.md, package-lock.json, src/config.ts, tslint.json
Some more linting (should be good now) and updated dependencies in the ReadMe file
=> Linting & ReadMe

src/views/about-us.ejs, src/views/about.ejs
Added "About us" and "Information" pages from the old website.
this resolve #63
=> Added "About us" and "Information" pages

package-lock.json, src/views/layout/header.ejs
https://github.com/savetheinternetinfo/website/issues/60
Omitted Images for now since the favicon is handled by Express
=> Added meta tags 

package-lock.json, src/views/contact-your-mep.ejs
Fix for https://github.com/savetheinternetinfo/website/issues/64
=> Corrected MEP detail

src/util/error.ts, src/views/500.ejs
Simple Error handling
Because i dont know how and where to handle the errors, i implemented a simple feature.
This function show a error 500 page and if the website is a dev version also the error message.
You can implement it or not, but it helps alot.
=> Implement error handling

src/views/privacy-policy.ejs
=> Correct size for heading

src/assets/css/main.scss
=> Fix wrong z-index in gallery

src/assets/css/shared/_global-components.scss, src/assets/js/main.ts, src/views/layout/header.ejs
The mobile menu isn't all that fancy, but it's better than hiding the menu all together.
Fixes #32
=> Add a rudimentary mobile menu.

src/views/about.ejs
This resolves https://github.com/savetheinternetinfo/website/issues/111
=> Removed comments

src/views/layout/header.ejs
Title says it all. This resolves https://github.com/savetheinternetinfo/website/issues/110
=> Added home button

src/controllers/router.ts
https://github.com/savetheinternetinfo/website/pull/122
=> Hotfix for route

src/assets/css/shared/_map.scss, src/languages/de.json, src/views/actionday.ejs, src/views/index.ejs
This PR adds map responsiveness
=> Changed Map frontend to match mobile devices

src/assets/css/shared/_map.scss, src/languages/de.json, src/views/actionday.ejs, src/views/index.ejs
* Changed Map frontend to match mobile devices
* fixed grammar for german translation
=> Changed Map frontend to match mobile devices (#124)

src/assets/css/shared/_map.scss, src/views/index.ejs
=> Fixed z-index for map

src/views/layout/header.ejs
Removed outdated ActionDay Link from Navbar
=> Navbar patch

src/controllers/router.ts, src/languages/de.json, src/languages/en.json, src/views/pressreview.ejs
Temporary disabled Pressreview and added a placeholder for Ger/En
=> Disabled Pressreview in router and added placeholder Text

src/views/imprint.ejs, src/views/privacy-policy.ejs
=> Fix for Important stuff

mapcoords.json
Also: No overly verbose PR anymore, yay
=> Fixed month

src/controllers/router.ts, src/languages/de.json, src/languages/en.json, src/languages/es.json, src/languages/fr.json, src/languages/it.json, src/languages/pt.json
Replaced STI ActionDay with Demo and added Vary header for Varnish Cache
=> Navbar/demo (#201)

mapcoords.json, src/assets/js/demomap.ts, src/controllers/router.ts, src/views/demos.ejs, src/views/demos_iframe.ejs
Here we go! I've changed the GeoJSON file. The Syntax now is:
```json
{
"type":"Feature",
"properties":[
{
"name":"Where?",
"value":"Köln"
},
{
"name":"When?",
"value":"February 16 – 13:30 – Neumarkt"
}
],
"geometry":{
"type":"Point",
"coordinates":[
6.932545,
50.936526
]
}
}
```
for example this is one Marker on the Map. One major change is here: The `properties` is now an Array instead of an object! Why? Simply because the adding of new values is easier now! Simply copy one object within the `properties` array and change `name` to the Title and `value` to the value.
Further the Map is now available as iframe! Simply under `/demos/iframe` if requested im gonna add the ability to change some settings simply by changing the URL.
CSS look now "cleaner". Removed border from popup and change …
=> Improvements to the map!

mapcoords.json, src/assets/js/demomap.ts, src/controllers/router.ts, src/languages/de.json, src/languages/en.json, src/languages/es.json, src/languages/fr.json, src/languages/it.json, src/languages/pt.json, src/services/DemomapService.ts, src/views/demos.ejs
This implements the translation for the map. It's dirty but it works. implementation > quality
=> Implement translation for the Map

mapcoords.json
Update start location Berlin & Bucharest
Removed Cologne
=> Updaten der Demos

src/languages/nl.json
Important Typo fix for NL on every page in header
=> Language/nl (#234)

mapcoords.json
I've entered the wrong date. Fixed within this commit!
=> Change the Date of the Demos

src/services/DemomapService.ts, yarn.lock
=> Fixed Joi schema

mapcoords.json
Announcement of demonstration on Twitter: https://twitter.com/MrMichalzik/status/1103612128903286785
Disclaimer: I'm not affiliated with the organisators of the demo.
=> Add demo on 23rd March in Germany, Würzburg to map

src/assets/js/partners.ts
Somebody maybe changed the content type and that maybe broke the shit *hust*
=> Fixed Partners

mapcoords.json
* Bremen Fixed
* Kiel FB event
=> Demo/correct2 (#295)

mapcoords.json
=> Added demos (#302)

mapcoords.json, src/views/demos.ejs
I start getting afraid of demos and public places
=> Demos everywhere
